import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "../context/authContext";
import { ThemeProvider } from "@/components/theme-provider";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/sidebar/app-sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <SidebarProvider
            style={
              {
                "--sidebar-width": "350px",
              } as React.CSSProperties
            }
          >
          <ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
            <AppSidebar />
            <div className="bg-slate-600 absolute left-10 top-10 items-center justify-center hidden max-md:flex">
              <SidebarTrigger />
            </div>
            {children}
          </ThemeProvider>
          </SidebarProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
